### ISSUE TITLE
Share my Dockerfile 

### ISSUE THREAD

**Issue by 0000sir** [vinthony/video-retalking#231]
The instructions in readme is a bit outdated, python 3.8, cuda 11.1 is not fit with 4090, I updated it and tested fine. Finally it works, but not as good as expected. Here comes the Dockerfile:
```
FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04
RUN apt-get update -y && DEBIAN_FRONTEND=noninteractive apt-get install -yq ffmpeg build-essential cmake
RUN apt-get install -y python3.10 python3-pip
RUN pip install torch==2.0.0+cu118 torchvision==0.15.0+cu118 -f https://download.pytorch.org/whl/torch_stable.html
COPY ./video-retalking /src/
WORKDIR /src
RUN pip install -r requirements.txt --default-timeout=600
```

and the compose file:
```
version: "3"
services:
  retalking:
    build: 
      context: .
      dockerfile: Dockerfile
    tty: true
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./video-retalking:/src
      - ./files:/files
      - ./checkpoints:/src/checkpoints
```

Hope this will help someone struggled in running errors.
